spring.application.name=emplyee-manager-sysetm
spring.datasource.url="Your DB_URL"
spring.datasource.username=root
spring.datasource.password="DB_PASSWORD"
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username="YOUR GMAIL"
spring.mail.password="YOUR APP PASSWORD"
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

jwt.secret="YOURSECURIT"
jwt.expiration=86400000